name: limelight
description: The number 1 recipe app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttericon: ^2.0.0
  google_fonts: ^3.0.1
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Leafy Greeens.jpg
    - assets/Vegetables.webp
    - assets/Meat.jpg
    - assets/Fish.jpg
    - assets/Shopping List.jpg
    - assets/Recipes.jpg
